name: xy_trans
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - defaults
dependencies:
  - blosc=1.21.6
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - et_xmlfile=2.0.0
  - freeglut=3.8.0
  - freexl=2.0.0
  - gdal=3.11.4
  - geos=3.10.6
  - geotiff=1.7.0
  - jpeg=9e
  - krb5=1.21.3
  - lerc=4.0.0
  - libarchive=3.8.2
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcurl=8.18.0
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgdal-core=3.11.4
  - libhwloc=2.12.1
  - libiconv=1.18
  - libkml=1.3.0
  - liblapack=3.11.0
  - libmpdec=4.0.0
  - libpng=1.6.54
  - libspatialite=5.1.0
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - lz4-c=1.9.4
  - minizip=4.0.6
  - mkl=2025.3.0
  - numpy=2.4.1
  - openpyxl=3.1.5
  - openssl=3.6.0
  - pcre2=10.46
  - pip=25.3
  - proj=9.3.1
  - python=3.13.11
  - python_abi=3.13
  - setuptools=80.9.0
  - snappy=1.2.2
  - sqlite=3.51.1
  - tbb=2022.3.0
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - uriparser=0.9.8
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xerces-c=3.3.0
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - attrs==25.4.0
      - certifi==2026.1.4
      - click==8.3.1
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - colorama==0.4.6
      - coord-convert==0.2.1
      - fiona==1.10.1
      - pandas==2.3.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - six==1.17.0
      - tqdm==4.67.1
      - tzdata==2025.3
